### ISSUE TITLE
cannot open directory in read-only mode

### ISSUE THREAD

**Issue by shengc** [DmitryKey/luke#57] opened 2016-04-20 18:51 UTC
I used to be able to open a directory even if it is being used by the other process through luke as long as I checked the "read-only mode" (before Lucene 5). But now I cannot,

    java.nio.file.AccessDeniedException: **/lucene/cache/write.lock

Is it a known issue ?

**Comment by shengc** [comment] 2016-04-21 01:19
the problem is `directory.obtainLock(WRITE_LOCK_NAME).close();` can throw `java.nio.file.AccessDeniedException` which the `try` block in ` in `IndexWriter.isLocked` does not catch. This seems to be fixed in the master. Is it possible to port it back to `luke-5.4.0`, and publish a fixed version of it ?

**Comment by DmitryKey** [comment] 2016-04-21 17:18
hi @shengc let me take a look.

**Comment by DmitryKey** [comment] 2016-05-17 10:09
@shengc The "Open In Read-Only mode" feature works for me with luke-5.4.0 and 5.4.1 index. Could you try with 5.4.1 to see if it is reproducible?

**Comment by fhopf** [comment] 2016-10-04 12:38
Tested this on Linux and luke-5.4.0 as well, no problems.

**Comment by DmitryKey** [comment] 2016-10-04 16:30
@fhopf thanks for validating, closing for now.

**Closed by DmitryKey** 2016-10-04 16:30 UTC
