### ISSUE TITLE
JavaFX exception

### ISSUE THREAD

**Issue by DmitryKey** [DmitryKey/luke#103] opened 2018-02-28 17:53 UTC
Source of the report: http://dmitrykan.blogspot.fi/2018/01/new-luke-on-javafx.html

```
Can anyone help me fix this error.
java.lang.NullPointerException: Location is required.
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3207)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
at application.Main.start(Main.java:15)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
at java.lang.Thread.run(Thread.java:745)﻿
```

**Comment by DmitryKey** [comment] 2018-02-28 17:54
@mocobeta does this report contain enough info to reproduce and debug the issue?

**Comment by mocobeta** [comment] 2018-03-04 14:08
Seems the error occurred when launching Luke, but I could not figure out what is wrong with. I will investigate the issue. 
OS, Java version, locale,  or other platform information will help us to reproduce the error...

**Comment by DmitryKey** [comment] 2018-03-12 19:59
yeah, I have asked the user on the blog, but no reply.

**Comment by MaximKulikov** [comment] 2018-03-13 18:05
I checked, but cannot reproduce bug. Would be better if he post full exception, since it ussualy contain severals sections and last one point to place you're looking.
But at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3207) indicates that issue with fxml file at first argument. (Probably Path war  / vs \ os specific, wierd national symbols is absolute path, dark magic). I dont have more idea at this tim, sorry :(

**Comment by mocobeta** [comment] 2018-10-04 05:37
There is no further information to dig it. For cleaning up, I close this issue.

**Closed by mocobeta** 2018-10-04 05:37 UTC
